### PR TITLE
refactor: use injectable service and providers

### PR DESCRIPTION
**Pull request by santoshyadavdev**
The PR uses Angular way of using AppWriteService, this goes more in a way Angular Standard to inject the service.

The APP_INITIALIZER will be responsible for initializing the AppWrite service so instance is available before it is being used

### CODE REVIEW

**Comment by santoshyadavdev** [comment]
Can someone check the API is giving some error or did i made some mistake 
Cc: @brandonroberts

**Comment by brandonroberts** [comment]
@santoshyadavdev if you're using the PR preview, you will most likely get a CORS error because the subdomain isn't added to the platforms for this project. What's the error?

**Comment by santoshyadavdev** [comment]
> @santoshyadavdev if you're using the PR preview, you will most likely get a CORS error because the subdomain isn't added to the platforms for this project. What's the error?

Yes it it CORS error.

**Comment by eldadfux** [comment]
@brandonroberts, once 0.14 is out, we should probably use the new wildcard hostname for these demo apps.

**Comment by brandonroberts** [comment]
Yep, I was thinking the same thing

**Pull request closed without merging**
